apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
  labels:
    name: mongo-deploy
    app: microservice-libreria
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: microservice-libreria
      name: mongo-pod
    template:
      metadata:
        name: mongo-pod
        labels:
          app: microservice-libreria
          name: mongo-pod
      spec:
        container:
          - name: mongo
            image: mongo:7.0.14-rc0-nanoserver-ltsc2022
            command:
            - /bin/bash
            - -c
            env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "andrudev29"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "Andr3sG2024*"
            ports: 
             - containerPort: 27017