apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  labels:
    app: microservice-libreria
    name: mongo-pod
spec:
  container:
    - name: mongo
      image: mongo:7.0.14-rc0-nanoserver-ltsc2022
      command:
      - /bin/bash
      - -c
      env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: "andrudev29"
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: "Andr3sG2024*"
      ports: 
       - containerPort: 27017